### ISSUE TITLE
Feature request to support Async Creatable in addition to Async Select.

### ISSUE THREAD

**Issue by jesse10581** [guiyep/react-select-virtualized#1]
Unless I'm mistaken, there is no way to add items to the list.  Is there any reason not to just include Creatable instead of Select based on some prop?  Is there a performance penalty with large data sets?

**Comment by guiyep** [comment]
Hello Jesse,

Unfortunately there is not right now. I looked in the doc and the creatable
select itself it is not the problem but the way they manage the list. Since
everything in the pop out list is custom made in my component I will have
to review the case ( this is entirely for performance reasons). So, I will
add this as a feature and add it to the component roadmap.

Thanks for letting me know!

**Comment by guiyep** [comment]
Async Select is supported in 1.1.0 now. I will finish grouping an later move to creatabale.
