### ISSUE TITLE
Can't reset value programmatically ! 

### ISSUE THREAD

**Issue by dhirajbasukala** [guiyep/react-select-virtualized#15]
Firstly, thank you for the awesome component. I had it implemented and it work just as expected. I have the latest version of react-select, react-select-virtualized library set up. The clear (x) button work as expected, which to my understanding is, resets the value to null.  I have a small implementation at [here](https://codesandbox.io/s/cool-frog-6p6tt). 
While there are two `<Select>` widget among other in the form. The reset function to reset states to initial state won't work even if I set values properties to "null" for the `<Select>` widgets. Any insights and tips is greatly appreciated. Thank you for you time.

**Comment by guiyep** [comment]
Hello Mate,

Thanks for opening the ticket. One of the things I need to mentions is that you need to use `value` instead of `defaultValue` so you can use the component as a controlled component. Apart from that, I found an issue that is going to be fixed in the next version (2.0.20), It already pushed. but npm can take some time to update the package

I also updated the docs because it looks like it was not clear.  :)

thanks!
guiyep

**Comment by guiyep** [comment]
here you have an example: https://serene-hawking-021d7a.netlify.com/?path=/story/react-select-virtualized-props--with-value-controlled

**Comment by dhirajbasukala** [comment]
Thank you for the prompt resolution. I updated the example with the latest version 2.0.20 and still it was not working. I removed default value property and replaced it with value but still it was not woking as expected. The thing that worked with me was supplying value as array. ie instead of `value={this.state.selectedData}` array type worked such as. `value={[this.state.selectedData]}`. I am posting it just in case someone else might stumble upon it in future. Thank you for the wonderful work.
