### ISSUE TITLE
use of react-window

### ISSUE THREAD

**Issue by Arjun-sna** [guiyep/react-select-virtualized#152]
Is it possible `react-virtualized` dependency be replaced by `react-window` since `react-window` is light-weight?

**Comment by guiyep** [comment]
hello,

Thanks for using react-select-virtualized.

This request is outside the scope of this library. I had in my plans the idea of being able to use one or the other but this library does not only rely on the window component. At the same time, it cannot be replaced entirely because many people use this library because they already use react-virtualized in their projects. It needs to be an approach where we can use both.

Thanks again,
Guiyep.
