### ISSUE TITLE
Keyboard navigation

### ISSUE THREAD

**Issue by danberger1** [guiyep/react-select-virtualized#17]
Keyboard navigation (that does exist on react-select),
doesn't work when using the react-select-virtualized version.
(Checked it on latest versions).

Is that a bug? or wasn't developed yet?

**Comment by M-Yankov** [comment]
Maybe look at #12

**Comment by guiyep** [comment]
Hello,

The feature was present and working and I had to disable it because the broke it.

Still it is not fixed, the issue from react-select is still open and I validated this, their issue is still present.

I don’t know what are they doing... they keep braking things lately. I hope they get to an stable version soon.

Thanks for using the library!
