### ISSUE TITLE
Make the LAG_INDICATOR configurable

### ISSUE THREAD

**Issue by MatanBorenkraoutNielsen** [guiyep/react-select-virtualized#256]
Hi there! :)
We're working with the Virtualized Select as a drop-in replacement for react-select when using large amount of items. 
We've encountered a problem where the code in `FastReactSelect` uses the `AsyncSelect` from react-select once the number of items is higher than the `LAG_INDICATOR` (which is 1K constant), this changes the native behavior for the select and makes it pretty complicated to make the VirtualizedSelect a drop-in replacement..
Any chance to set the LAG_INDICATOR as a prop? 
I'd be glad to create a PR for that one if you think this is something you'd want to support.

Thanks for the hard work maintaining this package!

**Comment by guiyep** [comment]
Hello Mate,

Sorry, can you explain a little bit more the reason that is a problem?

That indicator is in there because from that point onwards the render of the select gets heavy and we need to reduce the amount of data to display and manage. That is being done just internally l. From someone using it it won’t matter.

**Comment by MatanBorenkraoutNielsen** [comment]
Hi @guiyep, thanks for the quick response!

Basically our use case is that we have a wrapper around the select and we manage the `isOpen` state on our own, means we show the Select only when our `isOpen` state is set to `true` and always pass `menuIsOpen: true`. We either render VirtualizedSelect/Select based on our logic.
In `FastReactSelect` you decide which `Select` component to render and every Select with more than 1K elements has to use `ReactAsync` (which behaves differently since it doesn't open at first and just waits for a value to be entered to the search)..
The problem we encounter is that in selects with more than 1K elements we can't really control the `menuIsOpen`.
If I'll simplify our code, it will look like this:

```
isUsingVirtualized ? <VirtualizedSelect {...props} isMenuOpen/>:<Select {...props} menuIsOpen/>
```

The problem is that when using `VirtualizedSelect`, I can't be sure that `isMenuOpen` actually opens the select since for more than 1K options, it doesn't do that..

Hope I explained it better now :)

**Comment by guiyep** [comment]
Thanks for the explanation!

 I think then following your explanation what the component is lacking is the menuIsOpen for Async select. If you are happy to do a PR, What if instead modifying the core logic of how I manage internally the data(that would impact how the component works internally and can generate bugs) You just pass down the menu is open to the async select and pre-populate the data in that component?

I would happy review the PR.

Otherwise I can work on it but I can’t promise exactly when since I have been really busy with work lately :(

Thanks!

**Comment by MatanBorenkraoutNielsen** [comment]
Sure, I'd be glad to work on it!
Just to see that we're on the same page regarding the fix,
In [here](https://github.com/guiyep/react-select-virtualized/blob/master/src/components/fast-react-select/FastReactSelect.jsx#L127)

I'll change it to something like:
```
menuIsOpen={minimumInputSearchIsSet ? !!menuIsOpenState[menuIsOpenState.currentInput] : props.menuIsOpen}
```

(This isn't final of-course, just want to be sure).
Do you think this should be added to the options where you render `ReactSelectAsyncCreatableSelect` also?

**Comment by guiyep** [comment]
That is right! it would need to be added to all the supported components I think. Unless there is some technical limitation.

**Comment by MatanBorenkraoutNielsen** [comment]
Cool, I'll work on that then 👍

**Comment by MatanBorenkraoutNielsen** [comment]
Done :) Please let me know if you see any problem @guiyep..
