### ISSUE TITLE
It fails if `regeneratorRuntime` isn't installed

### ISSUE THREAD

**Issue by fregante** [guiyep/react-select-virtualized#283]
The built file has a reference to `regeneratorRuntime`:

https://www.unpkg.com/browse/react-select-virtualized@3.0.0/dist/index.min.js

Which works if it exists in the codebase, but it throws an error when it doesn't. `react-select` has a similar browser list config but it does not have any reference to `regeneratorRuntime` for some reason.

---

This is because the library is being transpiled with [the default `@babel/preset-env` configuration](https://github.com/guiyep/react-select-virtualized/blob/95ceec080779cc74e44b02b58ac24e322e432512/.babelrc#L2), which includes IE 11:

```js
❯ npx browserslist '> 0.5%, last 2 versions, Firefox ESR, not dead'
npx: installed 6 in 1.649s
and_chr 90
and_ff 87
and_qq 10.4
and_uc 12.12
android 90
baidu 7.12
chrome 91
chrome 90
chrome 89
edge 91
edge 90
firefox 89
firefox 88
firefox 78
ie 11
ios_saf 14.5-14.6
ios_saf 14.0-14.4
ios_saf 13.4-13.7
kaios 2.5
op_mini all
op_mob 62
opera 76
opera 75
safari 14.1
safari 14
samsung 14.0
samsung 13.0
```

**Comment by guiyep** [comment]
Will take a look at this soon

**Comment by guiyep** [comment]
Can you provide a codesandbox  example just for testing? I have An idea on what is wrong but I need some env for testing

**Comment by fregante** [comment]
As long as there's no reference of `regenerator` in the published file then it's all good!

**Comment by guiyep** [comment]
Sorry mate, I won't do it. I did the changes, but because of this, the package size went to 3 times the size. You will have to add the package yourself in your codebase I think. 99% of the people using this package already have everything needed to make it work (are you trying to use it with SSR?). If this becomes a problem for more people I can consider it but so far nobody has complained.
