### ISSUE TITLE
Default style not being applied to select element

### ISSUE THREAD

**Issue by dhirajbasukala** [guiyep/react-select-virtualized#3]
While the storybook shows component rendered with style, I am not getting the same results. I have created a demo of a forked react select example with this component applied. 
[https://codesandbox.io/s/react-codesandboxer-example-ne7od](https://codesandbox.io/s/react-codesandboxer-example-ne7od)
What am i missing ? Any help is appreciated. Thank you.

**Comment by guiyep** [comment]
Hello Dhiraj,

Can you try with the peer dependency of react-select ^2.4.4 I did not
update to the 3.0.0 version yet and since it is a major version it may
broke the library.

Let me know.
Guillermo

**Comment by guiyep** [comment]
I will Close this ticket since did not have any response.

**Comment by dhirajbasukala** [comment]
Hey guiyep, 
Sorry, I shared the link with dependency of 3.x.x version. I, however, have already tried with 2.4.4. I got it working by applying style to the classes with classNamePrefix applied. However, I would really like some more example codes in the site and storybook for quicker adoption, and show more actual code instead of Unknown tag for component, and functions names mentioned only in storybook. While I struggle to get it working,  the lack of good example are real let down. 
Thanks for the work so far.

**Comment by guiyep** [comment]
Sorry for your frustration. I see that now the component in storybook appears as Unknown. That is a bug that was introduces in the last storybook upgrade. and I'm going to fix it soon but it does not affect the example.

The library is full of examples. They are really easy to follow and you can use storybook for it. But basically it is what react-select support. Any extra prop is specified in the README.

I don't know what was happening with your case. Nobody has complained of anything since the start. It looks like there is some sort of problem between your peerDependencis, apart form the fact that react-select v3 has braking changes to v2.

I will work on that as separate thing.

Hope you still enjoy the library.
Guiyep.
