### ISSUE TITLE
Don't highlight hovered items in menu

### ISSUE THREAD

**Issue by DostoevskyMF** [guiyep/react-select-virtualized#4]

**Comment by guiyep** [comment]
Can you provide more context? I can see the hovering of the menu happening in storybook.

**Comment by DostoevskyMF** [comment]
U can see in this simple example. Maybe i use it somthing wrong.
https://codesandbox.io/s/morning-cookies-v3enj

**Comment by guiyep** [comment]
Hello,

You are not doing anything wrong. I will have to review the case. It looks like the virtualised items inside the list are not being loaded nor the css.

I tried an older version in your example with react-select 2.2 and it is not working neither. So It make me think that it may be related to the environment created by codesand. Otherwise this problem should have appeared long ago.

I will create an isolated test in a real environment and let you know.

Unfortunately i’m away until later next week.

I think that the other issue you opened it is pretty much related to the same.

Will back to you soon.

Guillermo.

**Comment by guiyep** [comment]
Fixed in 2.0.12

Try it: https://codesandbox.io/s/vigilant-mclean-wpbk7
