### ISSUE TITLE
Preventing autocomplete

### ISSUE THREAD

**Issue by Chris112** [guiyep/react-select-virtualized#43]
Is there a way to prevent form autocomplete using chrome? It looks like the input renders with autocorrect="off" which chrome ignores.

With React-Select you can pass in autoComplete="new-password" with InputProps to prevent this behaviour, just wondering if there was a way to do this?

`InputProps={{
               autoComplete: "new-password"
           }}`

**Comment by guiyep** [comment]
Hello Chris, 

First thanks for using the library.

unfortunately we can’t do that. I had to remove the ability to override compones from react-select since I had to override myself 4 of them to get the performance I wanted. I cannot relay on anyone changing them since that could change the behaviour of the component and break mine.

Maybe I can allow a subset of them, but I will have to check that, one by one.

Sorry,
Guiyep.
