### ISSUE TITLE
Select does not show the value when it is given as prop

### ISSUE THREAD

**Issue by SaraKoncz** [guiyep/react-select-virtualized#8]
Hello!
First of all thank you for this library, we can't wait to use it!
However, there is one blocking issue that we experienced: when provided the `value` as prop, the rendered _Select_ component does not show it, moreover it is possible to change the value by picking another option in the dropdown. 

I forked your sandbox example and reproduced the issue, you may find the link below:
[https://codesandbox.io/embed/admiring-mirzakhani-8wi94](https://codesandbox.io/embed/admiring-mirzakhani-8wi94)

This is how we would expect it to work (exact same code but with raw react-select):
[https://codesandbox.io/embed/zealous-payne-tztiu](https://codesandbox.io/embed/admiring-mirzakhani-8wi94)

You can see that the `onChange` is triggered in both cases.
We would like to use it as a controlled component, any information how we should manage it would be very much appreciated!

**Comment by guiyep** [comment]
Hello SaraKnocz,

Thanks for the info. I know about this and unfortunately I build the
component as an uncontrolled component with a default value when I first
did it at the beginning, that it why you can use the select method in the
ref for accomplishing this right now.

I have plans to include what you are asking for.

I have the changes for what you are requesting ( with the creatable select
implementation also) in a separate branch. I think I’m going to just pick
this feature and do a minor release and release The other feature later
since it has a bigger impact.

I will let you know when it is out.will need to be backwards compatible so
everyone can still use the library, so I will let you know when it is done.

Thanks,
Guiyep.

**Comment by guiyep** [comment]
I have finished the changes, I will do some more testing to make sure that everything works all right and will publish the changes. 

They will be available for tomorrow morning EST time.

Will let you know when everything is in.

Thanks,
guiyep

**Comment by guiyep** [comment]
I have fixed this issue in #2.0.16.

Thanks!

**Comment by SaraKoncz** [comment]
Hi Guiyep!

Thank you so-so much for your quick action and help! I cloned your code and tested in Storybook, it works perfect! 👍 
Unfortunately it somehow does not work when I update the npm package (to v2.0.17.) in our code, nor when I check the sandbox example that you provide - like it didn't update the code in the package? Could you please have a look?

Many thanks in advance!

**Comment by guiyep** [comment]
Great news!

Sometime npm takes a couple of hours to fully refresh the package.

We will have to wait :(. As soon as I wake up tomorrow I will check again
and let you know.

Thanks!

**Comment by guiyep** [comment]
It has been very strange but npm was not pushing my package latest version so I had to create a new one with no changes but only bumping the version. So please use v2.0.18.

here is an example:

https://codesandbox.io/s/peaceful-merkle-9s3vz

Cheers!

**Comment by SaraKoncz** [comment]
Hi Guiyep!

Thank you so much for the fix, works perfect in our project as well :) 

Cheers and thanks again!
